#!/bin/sh
#
# Post removal script for Jetrix
#

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
  purge)
    # remove the log files
    rm -Rf /var/log/jetrix

    # remove the symbolic link in /usr/games
    rm -f /usr/games/jetrix

    # remove the unpacked jars in the lib directory
    rm /usr/share/jetrix/lib/*.jar

    # unregister Jetrix from the boot sequence
    update-rc.d jetrix remove >/dev/null || exit $?

    # remove the jetrix user
    if [ -x "$(command -v deluser)" ] ; then
      if getent passwd|grep -q ^jetrix: ; then
        deluser --quiet --system jetrix > /dev/null || true
      fi
    else
      echo >&2 "not removing 'jetrix' system account because deluser command was not found."
    fi
  ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
