#!/bin/sh
#
# Pre installation script for Jetrix
#

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# Create the installation directory
mkdir -p /usr/share/jetrix
chmod a+w /usr/share/jetrix

exit 0
