#!/bin/sh

JETRIX_HOME="/usr/share/jetrix";

ln -s $JETRIX_HOME/jetrix /usr/games/jetrix

# move the conf directory to /etc/jetrix and create a symbolic link
mv $JETRIX_HOME/conf /etc/jetrix
ln -s /etc/jetrix $JETRIX_HOME/conf

# move the log directory to /var/log/jetrix and create a symbolic link
mv $JETRIX_HOME/log /var/log/jetrix
ln -s /var/log/jetrix $JETRIX_HOME/log
