#!/bin/sh
### BEGIN INIT INFO
# Provides:          tetrinet-server jetrix
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Init script for Jetrix
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=jetrix
DESC="Jetrix TetriNET Server"
DAEMON=/usr/share/jetrix/jetrix
USER=jetrix
GROUP=nogroup

test -x $DAEMON || exit 0

CONF=/etc/jetrix/server.xml
DAEMON_OPTS="--conf $CONF"
RUN="no"

# Include jetrix defaults if available
if [ -f /etc/default/$NAME ] ; then
  . /etc/default/$NAME
fi

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
    if [ "$RUN" != "yes" ] ; then
      log_warning_msg "Not starting $DESC $NAME, disabled via /etc/default/$NAME"
      exit 0
    fi

    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"

    start-stop-daemon --start --quiet --user $USER --chuid $USER:$GROUP --exec $DAEMON -- $DAEMON_OPTS

    case "$?" in
      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
      2)   [ "$VERBOSE" != no ] && log_end_msg 1 ;;
    esac
  ;;

  stop)
    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"

    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --user $USER

    case "$?" in
      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
      2)   [ "$VERBOSE" != no ] && log_end_msg 1 ;;
    esac
  ;;

  restart)
    [ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"

    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --user $USER

    case "$?" in
      0|1)
        start-stop-daemon --start --quiet --user $USER --chuid $USER:$GROUP --exec $DAEMON -- start $DAEMON_OPTS
        
        case "$?" in
          0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
          *) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
      ;;
      *) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
    esac
  ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
  ;;
esac

exit 0
